<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well">
            <h2><i class="icon-briefcase"></i> Danh Sách Bài Viết</h2>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                <tr>
                    <th>Tiêu Đề</th>
                    <th>Thuộc</th>
                    <th>Hình ảnh</th>
                    <th>SetHome</th>
                    <th>Trạng thái</th>
                    <th>Thao tác</th>
                </tr>
                </thead>
                <tbody>
                <?php if(isset($arrArticle) && $arrArticle && count($arrArticle)){ ?>
                    <?php foreach($arrArticle as $item){?>

                        <tr>
                            <td ><?php echo $item->title; ?></td>
                            <td class="center"><?php echo $item->name; ?></td>
                            <td width="20%" class="center"><img width="90%" alt="<?php echo isset($item) && isset($item->name) && $item->name ? $item->name : '' ; ?>" src="<?php echo isset($item) && isset(unserialize($item->properties)['avata']) && unserialize($item->properties)['avata'] ? $this->basePath().'/img/admin/article/'.unserialize($item->properties)['avata'] : ''; ?>" class="" style="display: block;"/>
                            </td>
                            <td class="center">
                                <?php if($item->home == 1){ ?>
                                <a title="UnSetHome" class="btn btn-inverse" href="<?php echo $this->url('adarticle', array('action' => 'index'), array('query' => array('id' => $item->id, 'action' => 'unsethome', ))); ?>">
                                    <i class="icon-home icon-white"></i>
                                </a>
                                <?php } ?></td>
                            <td class="center"><?php echo $item->status == 1 ? status_1 : status_0; ?></td>
                            <td class="center">
                                <a title="View" class="btn btn-success" href="<?php echo $this->url('adarticle', array('action' => 'detail'), array('query' => array('id' => $item->id))); ?>">
                                    <i class="icon-zoom-in icon-white"></i>
                                </a>
                                <a title="Edit" class="btn btn-info" href="<?php echo $this->url('adarticle', array('action' => 'save'), array('query' => array('id' => $item->id))); ?>">
                                    <i class="icon-edit icon-white"></i>
                                </a>
                                <?php if($item->home != 1){ ?>
                                <a title="SetHome" class="btn btn-inverse" href="<?php echo $this->url('adarticle', array('action' => 'index'), array('query' => array('id' => $item->id, 'action' => 'sethome', ))); ?>">
                                    <i class="icon-home icon-white"></i>
                                </a>
                                <?php } ?>
                                <a title="Enable" class="btn btn-success" href="<?php echo $this->url('adarticle', array('action' => 'index'), array('query' => array('id' => $item->id, 'action' => 'enable', ))); ?>">
                                    <i class="icon-ok icon-white"></i>
                                </a>
                                <a title="Disable" class="btn btn-inverse" href="<?php echo $this->url('adarticle', array('action' => 'index'), array('query' => array('id' => $item->id, 'action' => 'disable', ))); ?>">
                                    <i class="icon-off icon-white"></i>
                                </a>
                                <a title="Delete" class="btn btn-danger" href="<?php echo $this->url('adarticle', array('action' => 'del'), array('query' => array('id' => $item->id))); ?>">
                                    <i class="icon-trash icon-white"></i>
                                </a>
                            </td>

                        </tr>
                    <?php }}else {?>
                    <tr>
                        <td colspan="7">
                            <?php echo $this->render('partial/result_not_found'); ?>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?php
            if(isset($arrArticle) && $arrArticle && count($arrArticle))
                echo $this->paginationControl($this->arrArticle, 'Sliding', 'partial/pagination',
                    array(
                        'route' => 'adarticle',
                        'action' => 'index',
                        'params' => array(
                            'name' => isset($_GET['name']) ? $_GET['name'] : '' ,
                            'cat_id' => isset($_GET['cat_id']) ? $_GET['cat_id'] : '',
                        ),
                    )
                ) ;
            ?>
        </div>
    </div><!--/span-->

</div>