<?php
$ses_id = session_id();
$file_dir = 'includes/counter/count.txt';
if(!isset($_SESSION['session_id'])){
    $_SESSION['session_id'] = 1;
    $content = file_get_contents($file_dir);
    $total = '';
    $lastDay = '';
    $online = '';
    if($content){
        $content = explode(",",$content);
        foreach($content as $key => $vaule){
            $vaule = $vaule + 1;
            if($key == 0)  $total = $vaule;
            if($key == 1)  $lastDay = $vaule.'#'.date("Y/m/d");
            if($key == 2)  $online = $vaule;
        }
    }
    $file = fopen($file_dir,"w+");
    fwrite($file, $total.','.$lastDay.','.$online);
    fclose($file);
}
function total($file_dir){
    $content = file_get_contents($file_dir);
    $total = '';
    if($content){
        $content = explode(",",$content);
        $total = $content[0];
    }
    return $total;
}
?>
<?php echo total($file_dir); ?>