<?php echo $this->doctype(); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <meta charset="utf-8">
    <title>Untitled Page</title>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/main.css')
        ->prependStylesheet($this->basePath() . '/css/skitter.styles.css')
        ->prependStylesheet($this->basePath() . '/css/highlight.black.css')
        ->prependStylesheet($this->basePath() . '/css/sexy-bookmarks-style.css')?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/highlight.js')
        ->prependFile($this->basePath() . '/js/jquery.skitter.js')
        ->prependFile($this->basePath() . '/js/jquery.animate-colors-min.js')
        ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
        ->prependFile($this->basePath() . '/js/jquery-1.6.3.min.js')
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/jquery.validate.js')
        ->prependFile($this->basePath() . '/js/common.js')
        ->prependFile($this->basePath() . '/js/jquery.js')
    ?>
    <script>

        $(function () {
            $('.box_skitter_large').skitter({ dots: true });
        });
    </script>
</head>
<body>
    <div class="wrapper">
        <div class="header">
            <div class="btn_share">
                <img src="img/s1.png" alt="logo hoangphat" />
                <img src="img/s2.png" alt="logo hoangphat" />
                <img src="img/s3.png" alt="logo hoangphat" />
            </div>
        </div>
        <div class="content">
            <div class="menu">
                <div class="logo">
                    <img src="img/logo.png" width="108px" alt="logo hoangphat" />

                </div>
                <div class="menu_top">
                    <ul class="menu_v">
                        <a href="#"><li class="active">Trang chủ</li></a>
                        <a href="#"><li>Giới thiệu</li></a>
                        <a href="#"><li>Dự án tiêu biểu</li></a>
                        <a href="#"><li>Không gian nội thất</li></a>
                        <a href="#"><li>Tin tức</li></a>
                        <a href="#"><li>Liên hệ</li></a>
                    </ul>
                </div>
            </div>
            <div class="slide">
                <div class="border_box" >
                    <div class="box_skitter box_skitter_large ">
                        <ul>
                            <li><a href="#cube"><img src="img/1.png" class="cube" /></a></li>
                            <li><a href="#cubeRandom"><img src="img/1.png" class="cubeRandom" /></a></li>

                        </ul>
                    </div>
                </div>

            </div>

            <div class="project">
                <div class="tab1_l">

                    <img src="img/pic1.png" alt="logo hoangphat" />
                    <div class="title_tab1">Dự án mũi né</div>

                </div>

                <div class="tab1_l" style="margin-right:0px">

                    <img src="img/pic1.png" alt="logo hoangphat" />
                    <div class="title_tab1">Dự án mũi né</div>

                </div>
                <div class="news_fi">
                    <div class="header_news_fi">Thông tin mới</div>
                    <ul class="n_e">
                        <li>Hưởng ứng ngày môi trường thế giới 05/6/2013</li>
                        <li>Hưởng ứng ngày môi trường thế giới 05/6/2013</li>
                        <li>Hưởng ứng ngày môi trường thế giới 05/6/2013</li>
                        <li>Hưởng ứng ngày môi trường thế giới 05/6/2013</li>

                    </ul>
                </div>
            </div>
        </div>


        <div class="footer">

            <div class="footer_left">Copyright Hoang Phat 2014</div>
            <div class="footer_right">Số lượt truy cập: 100</div>
        </div>
    </div>
</body>
</html>
