<?php
$title = 'Về chúng tôi';
$this->headTitle($title);
?>
<div class="banner">
    <div class="border-top"></div>
    <div class="inner_banner">
        <div class="top-cat note-top">
            <div class="note-top-right"></div>
        </div>
        <div class="cat note">
            <h3 style="font-size: 30px;"><span class="green-title">SHOP</span> CATEGORY</h3>
            <ul class="category">
                <?php if(isset($arrCat) && $arrCat){ foreach($arrCat as $cus){ ?>
                <li><a href="<?php echo $this->url('main', array('action' => 'category'), array('query' => array('cid' =>  $cus->id))); ?>"><?php echo $cus->name; ?></a></li>
                <?php }} ?>
            </ul>
            <div class="note-right"></div>
        </div>
        <div class="menu-top">
            <ul>
                <li><a href="<?php echo $this->url('main', array('action' => 'latest')); ?>" title="">Latest Items &nbsp;&nbsp;&nbsp;</a><span class="slash-menu">|</span></li>
                <li><a href="<?php echo $this->url('main', array('action' => 'saleoff')); ?>" title="">Sale Off &nbsp;&nbsp;&nbsp;</a><span class="slash-menu">|</span></li>
                <li><a href="<?php echo $this->url('main', array('action' => 'about')); ?>" title="">About Us &nbsp;&nbsp;&nbsp;</a><span class="slash-menu">|</span></li>
                <li><a href="<?php echo $this->url('main', array('action' => 'contact')); ?>" title="">Contact </a></li>
            </ul>
            <?php //echo $this->navigation('Navigation')->menu(); ?>
        </div>
        <div class="ad-inner-main" id="ad-inner-main">
            <div class="contac-detail-main">
                <div>
                    <p><span class="title">Về chúng tôi</span></p><br />
                </div>
                <div style="float: left;">
                    <div class="about-us">
                        <img src="<?php  echo $this->basePath(); ?>/img/aboutz.jpg"/>
                        <div class="about-caption">
                            Chánh Tây tự hào mang đến cho quý khách các sản phẩm gia dụng bằng thủy tinh, sành, sứ, inox với chất lượng cao, thiết kế tinh xảo với giá hấp dẫn.
                        </div>
                    </div>
                    
                    <div  class="about-us-right">
                        <div class="about-right-wrapper">
                            <img src="<?php  echo $this->basePath(); ?>/img/dosu.jpg" />
                            <div class="about-caption-bot">
                                <div class="left">Đồ Sứ</div>
                                <div class="right">Sang trọng</div>
                            </div>
                        </div>
                        <div class="about-right-wrapper">
                            <img src="<?php  echo $this->basePath(); ?>/img/inox.jpg" />
                            <div class="about-caption-bot">
                                <div class="left">Đồ Inox</div>
                                <div class="right">Tiện dụng</div>
                            </div>
                        </div>
                        <div id="none" class="about-right-wrapper">
                            <img src="<?php  echo $this->basePath(); ?>/img/thuytinh.jpg" />
                            <div class="about-caption-bot">
                                <div class="left">Đồ Thủy Tinh</div>
                                <div class="right">Tinh tế</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
