<div class="content-news">
    <div class="about-left">
        noi dung 1
    </div>
    <div class="about-right">
        <div class="blockInfo">
            <h4>thông tin liên hệ</h4>
            <ul class="lstInfo">
                <li>02 Chu Văn An, Phường Bình Thọ, Q.Thủ Đức, Tp.HCM</li>
                <li><img width="17" height="16" alt="phone" src="<?php echo $this->basePath().'/img/icon_info_phone.png' ?>"><strong>
                        (08) 2218.6188</strong></li>
                <li><img width="17" height="16" alt="mobile" src="<?php echo $this->basePath().'/img/icon_info_mobile.png' ?>"><strong>
                        0903.609.931</strong></li>
                <li><img width="16" height="16" alt="email" src="<?php echo $this->basePath().'/img/icon_info_mail.png' ?>">
                    <a title="lovegardencoffee@yahoo.com" href="mailto:lovegardencoffee@yahoo.com">
                        <span> lovegardencoffee@yahoo.com</span>
                    </a>
                </li>
            </ul>
            <form action="" method="post" class="frm" id="frmSendMail" name="frmSendMail">
                <span class="title">Nhận tin khuyến mãi</span>
                <fieldset>
                    <input type="text" value="Nhập email của bạn ..." onblur="if(this.value=='')this.value='Nhập email của bạn ...';" onfocus="if(this.value=='Nhập email của bạn ...')this.value='';" id="txtSendMail" name="email">
                    <input type="submit" value="" id="btnSendMail" name="btnSendMail">
                    <input type="hidden" name="act" value="newsletter">
                </fieldset>
            </form>
        </div>
    </div>
</div>