<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <meta charset="utf-8">
    <title>Untitled Page</title>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/Slide/jquery.ad-gallery.css')
        ->prependStylesheet($this->basePath() . '/css/skitter.styles.css')
        ->prependStylesheet($this->basePath() . '/css/highlight.black.css')
        ->prependStylesheet($this->basePath() . '/css/sexy-bookmarks-style.css')?>

    <!-- main styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/main.css')
        ->prependStylesheet($this->basePath() . '/css/skitter.styles.css')
        ->prependStylesheet($this->basePath() . '/css/highlight.black.css')
        ->prependStylesheet($this->basePath() . '/css/sexy-bookmarks-style.css')?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/highlight.js')
        ->prependFile($this->basePath() . '/js/jquery.skitter.js')
        ->prependFile($this->basePath() . '/js/jquery.animate-colors-min.js')
        ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
        ->prependFile($this->basePath() . '/js/jquery-1.6.3.min.js')
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/jquery.validate.js')
        ->prependFile($this->basePath() . '/js/common.js')
        ->prependFile($this->basePath() . '/js/jquery.js')
    ?>

    <!-- Product styles -->
    <link rel="stylesheet" type="text/css" href="/hoangphat/public/Slide/jquery.ad-gallery.css">

    <!-- Scripts -->
    <script src="/hoangphat/public/js/jquery-1.9.1.js"></script>
    <script type="text/javascript" src="/hoangphat/public/Slide/jquery.ad-gallery.js"></script>
    <script type="text/javascript">
        $(function () {
            var galleries = $('.ad-gallery').adGallery();
            $('#switch-effect').change(
                function () {
                    galleries[0].settings.effect = $(this).val();
                    return false;
                }
            );
        });
    </script>
    <link rel="stylesheet" href="/hoangphat/public/css/demo.css">
    <script src="/hoangphat/public/js/json2.js"></script>
    <script src="/hoangphat/public/js/jquery.collapse.js"></script>
    <script src="/hoangphat/public/js/jquery.collapse_storage.js"></script>
    <script src="/hoangphat/public/js/jquery.collapse_cookie_storage.js"></script>
    <script>
        $(function () {
            $('.box_skitter_large').skitter({ dots: true });
        });
    </script>

</head>
<body>
<div class="wrapper">
    <div class="header">
        <div class="btn_share">
            <img src="<?php echo $this->basePath().'/img/s1.png' ?>" alt="google hoangphat" />
            <img src="<?php echo $this->basePath().'/img/s2.png' ?>" alt="twitter hoangphat" />
            <img src="<?php echo $this->basePath().'/img/s3.png' ?>" alt="facebook hoangphat" />
        </div>
    </div>
    <div class="menu">
        <div class="logo">
            <img src="<?php echo $this->basePath().'/img/logo.png' ?>" width="108px" alt="logo hoangphat" />

        </div>
        <div class="menu_top">
            <ul class="menu_v">
                <a href="<?php echo $this->url('main', array('action' => 'index')); ?>"><li>Trang chủ</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'about')); ?>"><li>Giới thiệu</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'project')); ?>"><li>Dự án tiêu biểu</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'category')); ?>"><li class="active">Không gian nội thất</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'news')); ?>"><li>Tin tức</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'contact')); ?>"><li>Liên hệ</li></a>
            </ul>
        </div>
    </div>
    <div class="content">
<div class="column_left">
    <div class="menu_ver">
        <div class="header_menu_ver">Không gian nội thất</div>
        <div id="css3-animated-example">
            <?php
            if($arrCat){
                foreach($arrCat as $cate){
                    if($cate -> parent_id == 0){
                        $id = $cate -> id;
                        ?>
                        <h3 class="activev <?php if($parent_id == $id) echo 'open' ?> "><span class="arrows"></span><?php echo $cate -> name ?></h3>

                        <div>
                            <div class="content">
                                <ul class="m_n_v">
                                    <?php
                                    foreach($arrCat as $cate2){
                                        if($cate2 -> parent_id == $id){
                                            ?>
                                            <li class="<?php if($cateId == $cate2 -> id) echo 'active' ?>"><span class="arrows1"></span><a href="<?php echo $this->url('main', array('action' => 'category'), array('query' => array('id' => $cate2->id, 'parent_id' => $id,))); ?>"> <?php echo $cate2 -> name ?></a></li>
                                        <?php
                                        }
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>

                    <?php
                    }
                }
            }
            ?>

        </div>


    </div>
    <div id="sidebar">
        <?php echo $this->partial('sidebar'); ?>
    </div>
</div>
<div class="column_right">
    <div id="gallery" class="ad-gallery">
        <?php if(isset($arritem) && $arritem && count($arritem)){ ?>
        <div class="nen_bgs"></div>
        <div class="ad-image-wrapper">
        </div>
        <div class="ad-controls">
        </div>

        <div class="ad-nav">
            <div class="ad-thumbs">
                <ul class="ad-thumb-list">
                    <?php

                    foreach($arritem as $item){
                        isset($item->arr_images) && $item->arr_images ? $images = unserialize($item->arr_images)[0] : $images = '';
                    ?>
                        <li>
                            <a href="<?php  if($images) echo $this->basePath().'/img/admin/items/'.$images; ?>">
                                <img src="<?php  if($images) echo $this->basePath().'/img/admin/items/'.$images; ?>" title="<?php echo $item -> name ?> " class="image1">
                            </a>
                        </li>
                    <?php
                        }
                    ?>
                </ul>
            </div>
        </div>
        <?php
            }
        ?>
    </div>
    <div class="des">Mô tả</div>
    <div class="nd">
       <?Php if($category) echo $category -> description  ?>
    </div>
</div>
