<?php
$title = 'Liên Hệ';
$this->headTitle($title);
?>
<div class="banner">
    <div class="border-top"></div>
    <div class="inner_banner">
        <div class="top-cat note-top">
            <div class="note-top-right"></div>
        </div>
        <div class="cat note">
            <h3 style="font-size: 30px;"><span class="green-title">SHOP</span> CATEGORY</h3>
            <ul class="category">
                <?php if(isset($arrCat) && $arrCat){ foreach($arrCat as $cus){ ?>
                <li><a href="<?php echo $this->url('main', array('action' => 'category'), array('query' => array('cid' =>  $cus->id))); ?>"><?php echo $cus->name; ?></a></li>
                <?php }} ?>
            </ul>
            <div class="note-right"></div>
        </div>
        <div class="menu-top">
            <ul>
                <li><a href="<?php echo $this->url('main', array('action' => 'latest')); ?>" title="">Latest Items &nbsp;&nbsp;&nbsp;</a><span class="slash-menu">|</span></li>
                <li><a href="<?php echo $this->url('main', array('action' => 'saleoff')); ?>" title="">Sale Off &nbsp;&nbsp;&nbsp;</a><span class="slash-menu">|</span></li>
                <li><a href="<?php echo $this->url('main', array('action' => 'about')); ?>" title="">About Us &nbsp;&nbsp;&nbsp;</a><span class="slash-menu">|</span></li>
                <li><a href="<?php echo $this->url('main', array('action' => 'contact')); ?>" title="">Contact </a></li>
            </ul>
            <?php //echo $this->navigation('Navigation')->menu(); ?>
        </div>
        <div class="ad-inner-main" id="ad-inner-main">
            <div class="contac-detail-main">
                <div>
                    <p><span class="title">Liên hệ với chúng tôi</span></p><br />
                </div>
                <div style="float: left;">
                    <div class="left-contact">
                        <div class="address">
                            <div class="address-left"></div>
                            <div class="address-right"></div>
                            <div class="address-center"></div>
                            <div class="address-content">
                                <div class="address-content-inner"><h3>Địa chỉ</h3></div>
                            </div>
                        </div>
                        <div class="clear"></div>
                        <div class="contact-inner">
                            <p class="font_8" style="line-height: 1.3em;">
                                <span style="line-height: 1.3em; color: #545658;">
                                124/8 An Nhơn, P17, Q.Gò Vấp<br/>
                                Ho Chi Minh City, Viet Nam<br/>
                                </span>
                            </p>
                        </div>
                        <div class="clear"></div>
                        <div class="contact-map">
                            <iframe style="width: 100%;" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=vi&amp;geocode=&amp;q=124%2F8+An+Nh%C6%A1n,+Th%C3%A0nh+ph%E1%BB%91+H%E1%BB%93+Ch%C3%AD+Minh,+H%E1%BB%93+Ch%C3%AD+Minh,+Vi%E1%BB%87t+Nam&amp;aq=0&amp;oq=124%2F8+An+Nh%C6%A1n&amp;sll=37.0625,-95.677068&amp;sspn=34.861942,86.572266&amp;ie=UTF8&amp;hq=&amp;hnear=124+An+Nh%C6%A1n,+ph%C6%B0%E1%BB%9Dng+17,+G%C3%B2+V%E1%BA%A5p,+H%E1%BB%93+Ch%C3%AD+Minh,+Vi%E1%BB%87t+Nam&amp;t=m&amp;z=14&amp;ll=10.836662,106.676613&amp;output=embed"></iframe>
                        </div>
                    </div>
                    <div class="right-contact">
                        <div class="telephone">
                            <div class="telephone-left"></div>
                            <div class="telephone-right"></div>
                            <div class="telephone-center"></div>
                            <div class="telephone-content">
                                <div class="telephone-content-inner"><h3>Điện thoại</h3></div>
                            </div>
                        </div>
                        <div class="clear"></div>
                        <div class="contact-inner">
                            <h3 style="color: #545658; margin: 0; font-family: inherit;">0934 109 968</h3>
                        </div>
                        <div class="clear"></div>
                        <div class="contact-form">
                            <form method="post" action="">
                                <p>Tên Của Bạn *<br>
                                    <span class="contact"><input type="text" name="name"></span> </p>
                                <p>Email *<br>
                                    <span class="contact"><input type="text" name="email"></span> </p>
                                <p>Tiêu đề*<br>
                                    <span class="contact"><input type="text" name="subject"></span> </p>
                                <p>Nội dung<br>
                                    <span class="contact"><textarea rows="5" name="message"></textarea></span> </p>
                                <p><input style="background: #519CFF; color: white;" type="submit" value="Send"/></p>
                            </form>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
