<div class="content-news">
    <div class="about-left">
        noi dung 1
    </div>
    <div class="about-right">
            <h4>Công ty THHH MTV sản xuất gỗ Hoàng Phát</h4>
            <ul class="lstInfo">
                <li style="background: none">Địa Chỉ : 2380/2A Đường Vườn Lài, Khu Phố 2, Phường An Phú Đông, Quận 12, TpHCM</li>
                <li ><img width="17" height="16" alt="phone" src="<?php echo $this->basePath().'/img/icon_info_phone.png' ?>"><strong>
                        (08) 2218.6188</strong></li>
                <li><img width="17" height="16" alt="mobile" src="<?php echo $this->basePath().'/img/icon_info_mobile.png' ?>"><strong>
                        0903.609.931</strong></li>
                <li><img width="16" height="16" alt="email" src="<?php echo $this->basePath().'/img/icon_info_mail.png' ?>">
                    <a title="lovegardencoffee@yahoo.com" href="mailto:lovegardencoffee@yahoo.com">
                        <span>mrthanhthang@gmail.com</span>
                    </a>
                </li>
                <li><img width="17" height="16" alt="mobile" src="<?php echo $this->basePath().'/img/icon_info_mobile.png' ?>"><strong>
                        Show rom</strong></li>
                <li><img width="17" height="16" alt="mobile" src="<?php echo $this->basePath().'/img/icon_info_mobile.png' ?>"><strong>
                        0903.609.931</strong></li>
            </ul>

    </div>
</div>