<div class="slide">
    <div class="border_box" >
        <div class="box_skitter box_skitter_large ">
            <ul>
                <?php
                foreach($arrProductHome as $product){
                    isset($product->arr_images) && $product->arr_images ? $images = unserialize($product->arr_images) : $images = array('');
                    ?>
                    <li><a href="#cube"><img height="100%" src="<?php  if($images) echo $this->basePath().'/img/admin/items/'.$images[0]; ?>" class="cube" /></a></li>
                <?php
                }
                ?>
            </ul>
        </div>
    </div>
    <div class="bgslider"></div>

</div>

<div class="project">
    <div class="tab1_l">
        <div class="tab_img"><img width="100%" src="img/hinh1.png" alt="logo hoangphat" /></div>
        <div class="title_tab1"><h2>Phòng ngủ</h2></div>
    </div>

    <div class="tab1_l" style="margin-left: 17px">

        <div class="tab_img"><img width="100%" src="img/hinh2.png" alt="logo hoangphat" /></div>
        <div class="title_tab1"><h2>Phòng ngủ</h2></div>

    </div>
    <div class="news_fi">
        <div class="header_news_fi">Thông tin mới</div>
        <ul class="n_e">
            <li>Hưởng ứng ngày môi trường</li>
            <li>Hưởng ứng ngày môi trường</li>
            <li>Hưởng ứng ngày môi trường</li>
            <li>Hưởng ứng ngày môi trường</li>
        </ul>
    </div>
</div>