<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <meta charset="utf-8">
    <title>Untitled Page</title>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/Slide/jquery.ad-gallery.css')
        ->prependStylesheet($this->basePath() . '/css/skitter.styles.css')
        ->prependStylesheet($this->basePath() . '/css/highlight.black.css')
        ->prependStylesheet($this->basePath() . '/css/sexy-bookmarks-style.css')?>

    <!-- main styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/main.css')
        ->prependStylesheet($this->basePath() . '/css/skitter.styles.css')
        ->prependStylesheet($this->basePath() . '/css/highlight.black.css')
        ->prependStylesheet($this->basePath() . '/css/sexy-bookmarks-style.css')?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/highlight.js')
        ->prependFile($this->basePath() . '/js/jquery.skitter.js')
        ->prependFile($this->basePath() . '/js/jquery.animate-colors-min.js')
        ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
        ->prependFile($this->basePath() . '/js/jquery-1.6.3.min.js')
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/jquery.validate.js')
        ->prependFile($this->basePath() . '/js/common.js')
        ->prependFile($this->basePath() . '/js/jquery.js')
    ?>

    <script>
        $(function () {
            $('.box_skitter_large').skitter({ dots: true });
        });
    </script>

</head>
<body>
<div class="wrapper">
    <div class="header">
        <div class="btn_share">
            <img src="<?php echo $this->basePath().'/img/s1.png' ?>" alt="google hoangphat" />
            <img src="<?php echo $this->basePath().'/img/s2.png' ?>" alt="twitter hoangphat" />
            <img src="<?php echo $this->basePath().'/img/s3.png' ?>" alt="facebook hoangphat" />
        </div>
    </div>
    <div class="menu">
        <div class="logo">
            <img src="<?php echo $this->basePath().'/img/logo.png' ?>" width="108px" alt="logo hoangphat" />

        </div>
        <div class="menu_top">
            <ul class="menu_v">
                <a href="<?php echo $this->url('main', array('action' => 'index')); ?>"><li class="active">Trang chủ</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'about')); ?>"><li>Giới thiệu</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'project')); ?>"><li>Dự án tiêu biểu</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'category')); ?>"><li>Không gian nội thất</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'news')); ?>"><li>Tin tức</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'contact')); ?>"><li>Liên hệ</li></a>
            </ul>
        </div>
    </div>
    <div class="content">

<div class="slide">
    <div class="border_box" >
        <div class="box_skitter box_skitter_large ">
            <ul>
                <?php
                foreach($arrProductHome as $key => $product){
                    if($key == 0) $productTop = $product;
                    isset($product->arr_images) && $product->arr_images ? $images = unserialize($product->arr_images) : $images = array('');
                    ?>
                    <li><a href="#cube"><img height="100%" src="<?php  if($images) echo $this->basePath().'/img/admin/items/'.$images[0]; ?>" class="cube" /></a></li>
                <?php
                }
                ?>
            </ul>
        </div>
    </div>
    <div class="bgslider"></div>

</div>
<div class="project">
    <div class="tab1_l">
        <?php
            if($catHome){
            foreach($catHome as $cate){?>
            <div class="tab_img"><a href="<?php echo $this->url('main', array('action' => 'category'), array('query' => array('id' => $cate->id, 'parent_id' => $cate -> parent_id,))); ?>"><img width="100%" src="<?php if(isset($cate->image) && $cate->image) echo $this->basePath().'/img/admin/cats/'.$cate->image; ?>" /></a></div>
            <div class="title_tab1"><a href="#"><h2><?php echo $cate -> name ?></h2></a></div>
        <?php }} ?>
    </div>

    <div class="tab1_l" style="margin-left: 17px">

        <?php
        if($projectHome){
            foreach($projectHome as $project){
                $properties = unserialize( $project -> properties);
                isset($properties['avata']) ? $images = $properties['avata'] : $images = '';
            ?>
            <div class="tab_img"> <a href="<?php echo $this->url('main', array('action' => 'project'), array('query' => array('id' => $project->id, 'cateId' => $project -> cat_id,))); ?>"> <img width="100%" src="<?php  if($images) echo $this->basePath().'/img/admin/article/'.$images; ?>" alt="<?php $project -> title ?>" /></a></div>
            <div class="title_tab1"><a href="<?php echo $this->url('main', array('action' => 'project'), array('query' => array('id' => $project->id, 'cateId' => $project -> cat_id,))); ?>"><h2><?php echo $project -> title ?></h2></a></div>
        <?php }} ?>

    </div>
    <div class="news_fi">
        <div class="tab_img">
            <ul class="n_e">
                <?php
                    if($arrArticleHome){
                        foreach($arrArticleHome as $article){
                            ?>
                <li> <a href="#"> <?php echo substr( $article -> title ,0, 50 ); echo substr( $article -> title ,50 ) ? '...' : ''?> </a> </li>
                <?php }
                }
                ?>
            </ul></div>
        <div class="title_tab1"><h2>Tin Mới</h2></div>
    </div>
</div>