<?php
$title = 'Sản phẩm - '.$pro->name;
$this->headTitle($title);
?>
<script type="text/javascript">
    $(document).ready(function(){
        $('#cart').click(function(){
                $.ajax({
                    url: '<?php echo $this->url('main', array('action'=>'servCart')); ?>',
                    type: 'get',
                    data: 'key=' + <?php echo $pro->id; ?>,
                    async:false,
                    success: function(jsonValue){ 
                        
                        var getData = $.parseJSON(jsonValue);
                        $quantity = getData.cart;
                        $('.quantity').html($quantity);
                        $('#nf').fadeOut('fast');
                    },
                    error: function (){
                        alert('Error');
                    }
                });
            $('#nf').fadeIn('fast');
        });
        $('#close').click(function(){
           $('#nf').fadeOut('fast');
        });
        
        $('#thumb-pro-list').css({width: ($('#thumb-pro-list li').size()*100)});
        var $slide = setInterval( "thumbProSwitch(false)", 3000 );
        $('#thumb-pro-list').hover(
            function(){
                clearTimeout($slide);
            },
            function(){
                $slide = setInterval( "thumbProSwitch(false)", 3000 );
            }
        );
        $('#thumb-pro-list li').click(function(){
            var $src = $(this).find('img').attr('src');
            $('.img-pro').html(('<img src="'+$src+'"/>'));
        });
        $('.thumb-pro-back').click(function(){
            clearTimeout($slide);
            thumbProSwitch(true);
            $slide = setInterval( "thumbProSwitch(false)", 3000 );
        });
        $('.thumb-pro-forward').click(function(){
            clearTimeout($slide);
            thumbProSwitch(false);
            $slide = setInterval( "thumbProSwitch(false)", 3000 );
        }); 
    });
</script>
<div style="display: none;" id="nf">Bạn đã thêm sản phẩm <strong>"<?php echo $pro->name; ?>"</strong> vào gỏi hàng <a id="close">[close]</a></div>
<?php if(isset($pro) && isset($pro->arr_images) && $pro->arr_images) $images = unserialize($pro->arr_images);
        else $images = array('');
 ?>
<div class="banner">
    <div class="border-top"></div>
    <div class="inner_banner">
        <div class="top-cat note-top">
            <div class="note-top-right"></div>
        </div>
        <div class="cat note">
            <h3 style="font-size: 30px;"><span class="green-title">SHOP</span> CATEGORY</h3>
            <ul class="category">
                <?php if(isset($arrCat) && $arrCat){ foreach($arrCat as $cus){ ?>
                <li><a href="<?php echo $this->url('main', array('action' => 'category'), array('query' => array('cid' =>  $cus->id))); ?>"><?php echo $cus->name; ?></a></li>
                <?php }} ?>
            </ul>
            <div class="note-right"></div>
        </div>
        <div class="menu-top">
            <ul>
                <li><a href="<?php echo $this->url('main', array('action' => 'latest')); ?>" title="">Latest Items &nbsp;&nbsp;&nbsp;</a><span class="slash-menu">|</span></li>
                <li><a href="<?php echo $this->url('main', array('action' => 'saleoff')); ?>" title="">Sale Off &nbsp;&nbsp;&nbsp;</a><span class="slash-menu">|</span></li>
                <li><a href="<?php echo $this->url('main', array('action' => 'about')); ?>" title="">About Us &nbsp;&nbsp;&nbsp;</a><span class="slash-menu">|</span></li>
                <li><a href="<?php echo $this->url('main', array('action' => 'contact')); ?>" title="">Contact </a></li>
            </ul>
            <?php //echo $this->navigation('Navigation')->menu(); ?>
        </div>
        <div class="ad-inner-main" id="ad-inner-main">
        <div class="pro-detail-main">
            <div class="view-pro">
                <div class="img-pro" style="width: 400px;">
                    <img alt="<?php echo $pro->name; ?>" src="<?php  echo $this->basePath().'/img/admin/items/'.$images[0]; ?>"/>
                </div>
                <?php if($images && count($images) >1){ unset($images[0])?>
                <div class="list-pro-thumb">
                    <div class="slider-pro-thumb">
                        <div class="thumb-pro-back"></div>
                        <div class="thumb-pro-tray"  style="left: 0;">
                            <ul id="thumb-pro-list">
                                <?php foreach($images as $img){ ?>
                                <li class="thumb">
                                    <div><img src="<?php  echo $this->basePath().'/img/admin/items/'.$img; ?>"/></div>
                                </li>
                                <?php } ?>
                            </ul>
                        </div>
                        <div class="thumb-pro-forward" style=""></div>
                    </div>
                </div>
                <?php } ?>
            </div>
            <div class="info-pro">
                <?php
                    if(isset($pro->name) && $pro->name){
                        $name = explode(' ', $pro->name); 
                        $first = $name[0];
                        unset($name[0]);
                        $last = implode(' ', $name);
                    }
                ?>
                <h4><span class="blue-title"><?php echo isset($first) ? $first : ''; ?></span> <?php echo isset($last) ? $last : ''; ?></h4>
                <div class="pro-feature" style="margin: 0;">
    				<?php if(isset($pro->discount_percent) && $pro->discount_percent){ ?>
					<p><span class="label-pro">Giá cũ</span><span>:</span>&nbsp;&nbsp;&nbsp;&nbsp;<del><?php echo number_format($pro->price,0,",","."); ?> VNĐ</del></p>
                    <p><span class="label-pro">Giảm giá</span><span>:</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="orange-title"><?php echo $pro->discount_percent; ?> %</span></p>
                    <p><span class="label-pro">Giá mới</span><span>:</span>&nbsp;&nbsp;&nbsp;&nbsp;<span><?php echo number_format(($pro->price -($pro->price*$pro->discount_percent)/100),0,",","."); ?> VNĐ</span></p>
                    <?php }else{ ?>
                    <p><span class="label-pro">Giá</span><span>:</span>&nbsp;&nbsp;&nbsp;&nbsp;<span><?php echo $pro->price ? number_format($pro->price,0,",",".").' VNĐ' : 'Call'; ?></span></p>
                    <?php } ?>
                    <p><span class="label-pro">Ngày đăng</span><span>:</span>&nbsp;&nbsp;&nbsp;&nbsp;<span><?php echo date('d-m-Y', time($pro->date_create)); ?></span></p>
                    <p><span class="label-pro">Số lượt xem</span><span>:</span>&nbsp;&nbsp;&nbsp;&nbsp;<span><?php echo $pro->view; ?></span></p>
    			</div>
                <div class="pro-feature">
                    <div class="social-shares">
                    <ul>
                        <li>
            				<a target="_blank" href="http://www.facebook.com/share.php?u=<?php echo $url.$this->url('main', array('action' => 'product'), array('query' => array('pid' => $pro->id))); ?>">
            					<img src="<?php  echo $this->basePath(); ?>/img/facebook-share.png" class="no-preload">
            				</a>
            			</li>
    			         <li>
            				<a target="_blank" href="http://twitter.com/home?status=<?php echo $pro->name; ?> - <?php echo $url.$this->url('main', array('action' => 'product'), array('query' => array('pid' => $pro->id))); ?>">
            					<img src="<?php  echo $this->basePath(); ?>/img/twitter-share.png" class="no-preload">
            				</a>
            			</li>
    			         <li>		
            				<a onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;" href="https://plus.google.com/share?url={<?php echo $url.$this->url('main', array('action' => 'product'), array('query' => array('pid' => $pro->id))); ?>}">
            					<img alt="google-share" src="<?php  echo $this->basePath(); ?>/img/google-plus-share.png" class="no-preload">
            				</a>					
            			</li>
         			</ul>
                    <div class="clear"></div>
                </div>
                </div>
                <div>
                    <a href="javascript:void(0)" id="cart" class="button"><i class="icon-add"></i><span class="hidden-tablet"> Đặt Hàng</span></a>
                    <a href="<?php echo $this->url('main', array('action' => 'order'), array('query' => array('key' => $pro->id))) ?>" class="button"><i class="icon-order"></i><span class="hidden-tablet"> Mua Hàng</span></a>
                </div>
            </div>
            <?php if(isset($pro->description) && $pro->description){ ?>
            <div class="clear"></div>
            <div class="description">
                <h4><span class="blue-title">Thông</span> tin sản phẩm</h4>
                <div class="des-content">
                    <?php echo $pro->description; ?>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <?php } ?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
