<script type="text/javascript">
    $(function () {
        $('img.image1').data('ad-desc', 'Whoa! This description is set through elm.data("ad-desc") instead of using the longdesc attribute.<br>And it contains <strong>H</strong>ow <strong>T</strong>o <strong>M</strong>eet <strong>L</strong>adies... <em>What?</em> That aint what HTML stands for? Man...');
        $('img.image1').data('ad-title', 'Title through $.data');
        $('img.image4').data('ad-desc', 'This image is wider than the wrapper, so it has been scaled down');
        $('img.image5').data('ad-desc', 'This image is higher than the wrapper, so it has been scaled down');
        var galleries = $('.ad-gallery').adGallery();
        $('#switch-effect').change(
            function () {
                galleries[0].settings.effect = $(this).val();
                return false;
            }
        );
        $('#toggle-slideshow').click(
            function () {
                galleries[0].slideshow.toggle();
                return false;
            }
        );
        $('#toggle-description').click(
            function () {
                if (!galleries[0].settings.description_wrapper) {
                    galleries[0].settings.description_wrapper = $('#descriptions');
                } else {
                    galleries[0].settings.description_wrapper = false;
                }
                return false;
            }
        );
    });
</script>
<div class="column_left">
    <div class="menu_ver">
        <div class="header_menu_ver">Không gian nội thất</div>

        <div id="css3-animated-example">
            <h3 class="open activev"><span class="arrows"></span> Commercial</h3>
            <div>
                <div class="content">
                    <ul class="m_n_v">




                        <li><span class="arrows1"></span><a href="#"> Commercial 1</a></li>
                        <li><span class="arrows1"></span><a href="#">Commercial 2</a></li>
                        <li><span class="arrows1"></span><a href="#"> Commercial 3</a></li>
                        <li><span class="arrows1"></span><a href="#"> Commercial 4</a></li>
                    </ul>
                </div>
            </div>
            <h3><span class="arrows"></span> Home Office</h3>
            <div>
                <div class="content">
                    <ul class="m_n_v">




                        <li><span class="arrows1"></span> Home Office 1</li>
                        <li><span class="arrows1"></span>Home Office 2</li>
                        <li><span class="arrows1"></span> Home Office 3</li>
                        <li><span class="arrows1"></span> Home Office 4</li>
                    </ul>
                </div>
            </div>
            <h3><span class="arrows"></span> Commercial</h3>
            <div>
                <div class="content">
                    <ul class="m_n_v">




                        <li><span class="arrows1"></span> Commercial 1</li>
                        <li><span class="arrows1"></span>Commercial 2</li>
                        <li><span class="arrows1"></span> Commercial 3</li>
                        <li><span class="arrows1"></span> Commercial 4</li>
                    </ul>
                </div>
            </div>

            <h3><span class="arrows"></span>Home Office </h3>
            <div>
                <div class="content">
                    <ul class="m_n_v">




                        <li><span class="arrows1"></span> Home Office 1</li>
                        <li><span class="arrows1"></span>Home Office 2</li>
                        <li><span class="arrows1"></span> Home Office 3</li>
                        <li><span class="arrows1"></span> Home Office 4</li>
                    </ul>
                </div>
            </div>
        </div>
        <script>
            $("#css3-animated-example").collapse({
                accordion: true,
                open: function () {
                    this.addClass("open");
                    this.css({ height: this.children().outerHeight() });
                },
                close: function () {
                    this.css({ height: "0px" });
                    this.removeClass("open");
                }
            });
        </script>

    </div>

    <div class="menu_ver" style="margin-top:10px;">
        <div class="header_menu_ver" style="width:200px;">Hỗ trợ trực tuyến</div>

        <ul class="m_n_v">
            <li>Mr . Khoa : <span style="color:red;font-weight:bold">098655666</span>
                <img src="http://opi.yahoo.com/online?u=NICK_CUA_BAN&m=g&t=2"/>

            </li>
            <li>Mr . Khoa : <span style="color:red;font-weight:bold">098655666</span>

                <img src="http://opi.yahoo.com/online?u=NICK_CUA_BAN&m=g&t=2"/>
            </li>
            <li>Mr . Khoa : <span style="color:red;font-weight:bold">098655666</span>

                <img src="http://opi.yahoo.com/online?u=NICK_CUA_BAN&m=g&t=2"/>
            </li>

        </ul>
    </div>

    <div class="menu_ver" style="margin-top:10px;">
        <div class="header_menu_ver" style="width:160px;">Số lượng truy cập</div>

        <ul class="m_n_v">
            <li>Tất cả : 23339</li>
            <li>Hôm qua : 230</li>

        </ul>
    </div>
</div>
<div class="column_right">
    <div id="gallery" class="ad-gallery">
        <div class="nen_bgs"></div>
        <div class="ad-image-wrapper">
        </div>
        <div class="ad-controls">
        </div>
        <div class="ad-nav">
            <div class="ad-thumbs">
                <ul class="ad-thumb-list">

                    <li>
                        <a href="Slide/images/p.png">
                            <img src="Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="Slide/images/p.png">
                            <img src="Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="Slide/images/p.png">
                            <img src="Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="Slide/images/p.png">
                            <img src="Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="Slide/images/p.png">
                            <img src="Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="Slide/images/p.png">
                            <img src="Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="Slide/images/p.png">
                            <img src="Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <div class="des">Mô tả</div>
    <div class="nd">Chọn nơi an cư lạc nghiệp hay đầu tư sinh lợi luôn là một việc lớn đối với nhiều người, và khi đến với Lucky Home có thể hoàn toàn yên tâm về những điều đó.Chọn nơi an cư lạc nghiệp hay đầu tư sinh lợi luôn là một việc lớn đối với nhiều người, và khi đến với Lucky Home có thể hoàn toàn yên tâm về những điều đó.Chọn nơi an cư lạc nghiệp hay đầu tư sinh lợi luôn là một việc lớn đối với nhiều người, và khi đến với Lucky Home có thể hoàn toàn yên tâm về những điều đó.Chọn nơi an cư lạc nghiệp hay đầu tư sinh lợi luôn là một việc lớn đối với nhiều người, và khi đến với Lucky Home có thể hoàn toàn yên tâm về những điều đó.</div>
</div>