
<div class="column_left">
    <div class="menu_ver">
        <div class="header_menu_ver">Không gian nội thất</div>
        <div id="css3-animated-example">
            <?php
            if($arrCat){
                foreach($arrCat as $cate){
                if($cate -> parent_id == 0){
                    $id = $cate -> id;
            ?>
                <h3 class="activev"><span class="arrows"></span><?php echo $cate -> name ?></h3>

                <div>
                    <div class="content">
                        <ul class="m_n_v">
                            <?php
                                foreach($arrTreeCat as $cate2){
                                    if($cate2 -> parent_id == $id){
                            ?>
                            <li class="active"><span class="arrows1"></span><a href="#"> <?php echo $cate2 -> name ?></a></li>
                            <?php
                                    }
                                }
                            ?>
                        </ul>
                    </div>
                </div>

            <?php
                    }
                }
            }
            ?>




        </div>
        <script>
            $("#css3-animated-example").collapse({
                accordion: true,
                open: function () {
                    this.addClass("open");
                    this.css({ height: this.children().outerHeight() });
                },
                close: function () {
                    this.css({ height: "0px" });
                    this.removeClass("open");
                }
            });
        </script>

    </div>

    <div class="menu_ver" style="margin-top:10px;">
        <div class="header_menu_ver" style="width:200px;">Hỗ trợ trực tuyến</div>

        <ul class="m_n_v">
            <li>Mr . Khoa : <span style="color:red;font-weight:bold">098655666</span>
                <img src="http://opi.yahoo.com/online?u=NICK_CUA_BAN&m=g&t=2"/>

            </li>
            <li>Mr . Khoa : <span style="color:red;font-weight:bold">098655666</span>

                <img src="http://opi.yahoo.com/online?u=NICK_CUA_BAN&m=g&t=2"/>
            </li>
            <li>Mr . Khoa : <span style="color:red;font-weight:bold">098655666</span>

                <img src="http://opi.yahoo.com/online?u=NICK_CUA_BAN&m=g&t=2"/>
            </li>

        </ul>
    </div>

    <div class="menu_ver" style="margin-top:10px;">
        <div class="header_menu_ver" style="width:160px;">Số lượng truy cập</div>

        <ul class="m_n_v">
            <li>Tất cả : 23339</li>
            <li>Hôm qua : 230</li>

        </ul>
    </div>
</div>
<div class="column_right">
    <div id="gallery" class="ad-gallery">
        <div class="nen_bgs"></div>
        <div class="ad-image-wrapper">
        </div>
        <div class="ad-controls">
        </div>
        <div class="ad-nav">
            <div class="ad-thumbs">
                <ul class="ad-thumb-list">

                    <li>
                        <a href="/hoangphat/public/Slide/images/p.png">
                            <img src="/hoangphat/public/Slide/images/thumbs/p.png" title="Dai ca thang" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="/hoangphat/public/Slide/images/p.png">
                            <img src="/hoangphat/public/Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="/hoangphat/public/Slide/images/p.png">
                            <img src="/hoangphat/public/Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="/hoangphat/public/Slide/images/p.png">
                            <img src="/hoangphat/public/Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="/hoangphat/public/Slide/images/p.png">
                            <img src="/hoangphat/public/Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="/hoangphat/public/Slide/images/p.png">
                            <img src="/hoangphat/public/Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                    <li>
                        <a href="/hoangphat/public/Slide/images/p.png">
                            <img src="/hoangphat/public/Slide/images/thumbs/p.png" title="A title for 10.jpg" alt="This is a nice, and incredibly descriptive, description of the image 10.jpg" class="image1">
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="des">Mô tả</div>
    <div class="nd">Chọn nơi an cư lạc nghiệp hay đầu tư sinh lợi luôn là một việc lớn đối với nhiều người, và khi đến với Lucky Home có thể hoàn toàn yên tâm về những điều đó.Chọn nơi an cư lạc nghiệp hay đầu tư sinh lợi luôn là một việc lớn đối với nhiều người, và khi đến với Lucky Home có thể hoàn toàn yên tâm về những điều đó.Chọn nơi an cư lạc nghiệp hay đầu tư sinh lợi luôn là một việc lớn đối với nhiều người, và khi đến với Lucky Home có thể hoàn toàn yên tâm về những điều đó.Chọn nơi an cư lạc nghiệp hay đầu tư sinh lợi luôn là một việc lớn đối với nhiều người, và khi đến với Lucky Home có thể hoàn toàn yên tâm về những điều đó.</div>
</div>