<div class="column_left">
    <div class="menu_ver">
        <div class="header_menu_ver">Không gian nội thất</div>
        <div class="css3-animated-example">
            <?php
            if($arrCat){
                foreach($arrCat as $cate){
                    if($cate -> level == 0){
                        ?>
                        <h3 class="activev"><span style="margin-left: -1px;
    margin-top: 16px;" class="arrows"></span>
                           <a class="<?php if($cateId == $cate -> id) echo 'open'?>" title="" href="<?php echo $this->url('main', array('action' => 'project'), array('query' => array('cateId' => $cate -> id,))); ?>">
                               <?php echo $cate -> name ?>
                            </a>
                        </h3>
                        <div>
                        </div>
                    <?php
                    }
                }
            }
            ?>
        </div>
    </div>
    <div id="sidebar">
        <?php echo $this->partial('sidebar'); ?>
    </div>
</div>
<?php if($id){ ?>
<div class="column_right">
    <?php if($acticle){ ?>
        <h2><?php echo $acticle -> title ?></h2>
        <?php echo $acticle -> detail ?>
    <?php } ?>
</div>
<?php }else{ ?>
<div class="column_right">
    <?php
    if($arrCat){
        foreach($arritem as $item){
    ?>
    <div class="listNews">
        <div class="newleft">
            <a title="<?php echo $item -> title?>" href="<?php echo $this->url('main', array('action' => 'project'), array('query' => array('id' => $item->id, 'cateId' => $item -> cat_id,))); ?>">
                <img height="100px" alt="<?php echo $item -> title?>" src="<?php echo $this->basePath().'/img/new.jpg' ?>"></a>

        </div>
        <div class="newright">
            <h2><a title="<?php echo $item -> title?>" href="<?php echo $this->url('main', array('action' => 'project'), array('query' => array('id' => $item->id, 'cateId' => $item -> cat_id,))); ?>"><?php echo $item -> title?></a></h2>
            <p class="date"><?php echo $item -> date_created?></p>
            <?php echo $item -> description ?>
        </div>
    </div>
    <?php
        }
    }
    ?>
</div>
<?php } ?>