<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <meta charset="utf-8">
    <title>Untitled Page</title>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/Slide/jquery.ad-gallery.css')
        ->prependStylesheet($this->basePath() . '/css/skitter.styles.css')
        ->prependStylesheet($this->basePath() . '/css/highlight.black.css')
        ->prependStylesheet($this->basePath() . '/css/sexy-bookmarks-style.css')?>

    <!-- main styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/main.css')
        ->prependStylesheet($this->basePath() . '/css/skitter.styles.css')
        ->prependStylesheet($this->basePath() . '/css/highlight.black.css')
        ->prependStylesheet($this->basePath() . '/css/sexy-bookmarks-style.css')?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/highlight.js')
        ->prependFile($this->basePath() . '/js/jquery.skitter.js')
        ->prependFile($this->basePath() . '/js/jquery.animate-colors-min.js')
        ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
        ->prependFile($this->basePath() . '/js/jquery-1.6.3.min.js')
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/jquery.validate.js')
        ->prependFile($this->basePath() . '/js/common.js')
        ->prependFile($this->basePath() . '/js/jquery.js')
    ?>

    <!-- Product styles -->
    <link rel="stylesheet" type="text/css" href="/hoangphat/public/Slide/jquery.ad-gallery.css">

    <!-- Scripts -->
    <script src="/hoangphat/public/js/jquery-1.9.1.js"></script>
    <script type="text/javascript" src="/hoangphat/public/Slide/jquery.ad-gallery.js"></script>
    <script type="text/javascript">
        $(function () {
            var galleries = $('.ad-gallery').adGallery();
            $('#switch-effect').change(
                function () {
                    galleries[0].settings.effect = $(this).val();
                    return false;
                }
            );
        });
    </script>
    <link rel="stylesheet" href="/hoangphat/public/css/demo.css">
    <script src="/hoangphat/public/js/json2.js"></script>
    <script src="/hoangphat/public/js/jquery.collapse.js"></script>
    <script src="/hoangphat/public/js/jquery.collapse_storage.js"></script>
    <script src="/hoangphat/public/js/jquery.collapse_cookie_storage.js"></script>
    <script>
        $(function () {
            $('.box_skitter_large').skitter({ dots: true });
        });
    </script>

</head>
<body>
<div class="wrapper">
    <div class="header">
        <div class="btn_share">
            <img src="<?php echo $this->basePath().'/img/s1.png' ?>" alt="google hoangphat" />
            <img src="<?php echo $this->basePath().'/img/s2.png' ?>" alt="twitter hoangphat" />
            <img src="<?php echo $this->basePath().'/img/s3.png' ?>" alt="facebook hoangphat" />
        </div>
    </div>
    <div class="menu">
        <div class="logo">
            <img src="<?php echo $this->basePath().'/img/logo.png' ?>" width="108px" alt="logo hoangphat" />

        </div>
        <div class="menu_top">
            <ul class="menu_v">
                <a href="<?php echo $this->url('main', array('action' => 'index')); ?>"><li >Trang chủ</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'about')); ?>"><li>Giới thiệu</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'project')); ?>"><li class="active">Dự án tiêu biểu</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'category')); ?>"><li>Không gian nội thất</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'news')); ?>"><li>Tin tức</li></a>
                <a href="<?php echo $this->url('main', array('action' => 'contact')); ?>"><li>Liên hệ</li></a>
            </ul>
        </div>
    </div>
    <div class="content">
<div class="column_left">
    <div class="menu_ver">
        <div class="header_menu_ver">Không gian nội thất</div>
        <div class="css3-animated-example">
            <?php
            if($arrCat){
                foreach($arrCat as $cate){
                    if($cate -> level == 0){
                        ?>
                        <h3 class="activev"><span style="margin-left: -1px;
    margin-top: 16px;" class="arrows"></span>
                           <a class="<?php if($cateId == $cate -> id) echo 'open'?>" title="" href="<?php echo $this->url('main', array('action' => 'project'), array('query' => array('cateId' => $cate -> id,))); ?>">
                               <?php echo $cate -> name ?>
                            </a>
                        </h3>
                        <div>
                        </div>
                    <?php
                    }
                }
            }
            ?>
        </div>
    </div>
    <div id="sidebar">
        <?php echo $this->partial('sidebar'); ?>
    </div>
</div>
<?php if($id){ ?>
<div class="column_right">
    <?php if($acticle){
        if(isset($acticle -> properties['file']) && $acticle -> properties['file'])
        {
        ?>
            <div id="gallery" class="ad-gallery">
                    <div class="nen_bgs"></div>
                    <div class="ad-image-wrapper">
                    </div>
                    <div class="ad-controls">
                    </div>
                    <div class="ad-nav">
                        <div class="ad-thumbs">
                            <ul class="ad-thumb-list">
                                <?php
                                foreach($acticle -> properties['file'] as $images){
                                    ?>
                                    <li>
                                        <a href="<?php  if($images) echo $this->basePath().'/img/admin/article/'.$images; ?>">
                                            <img src="<?php  if($images) echo $this->basePath().'/img/admin/article/'.$images; ?>" title="" class="image1">
                                        </a>
                                    </li>
                                <?php
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
            </div>




        <?php  } ?>
        <div class="des"><?php echo $acticle -> title ?></div>
        <?php echo $acticle -> detail ?>
    <?php } ?>
</div>
<?php }else{ ?>
<div class="column_right">
    <?php
    if($arrCat){
        foreach($arritem as $item){
            ?>
    <div class="listNews">
        <div class="newleft">
            <a title="<?php echo $item -> title?>" href="<?php echo $this->url('main', array('action' => 'project'), array('query' => array('id' => $item->id, 'cateId' => $item -> cat_id,))); ?>">
                <img height="100px" alt="<?php echo $item -> title?>" src="<?php if(isset($item -> properties['avata']) && $item -> properties['avata']) echo $this->basePath().'/img/admin/article/'.$item -> properties['avata']; else echo $this->basePath().'/img/logo.png'?>"></a>

        </div>
        <div class="newright">
            <h2><a title="<?php echo $item -> title?>" href="<?php echo $this->url('main', array('action' => 'project'), array('query' => array('id' => $item->id, 'cateId' => $item -> cat_id,))); ?>"><?php echo $item -> title?></a></h2>
            <p class="date"><?php echo $item -> date_created?></p>
            <?php echo $item -> description ?>
        </div>
    </div>
    <?php
        }
    }
    ?>
</div>
<?php } ?>
    </div>
    <div style="clear: both"></div>
    <div class="footer">
        <div class="footer_left" style="color: #a84e2a">Copyright Hoang Phat 2014</div>
        <div class="footer_right" style="color: #a84e2a">Số lượt truy cập: </div>
    </div>
</div>
</body>
</html>
