
<div class="column_left">
    <div class="menu_ver">
        <div class="header_menu_ver">Không gian nội thất</div>
        <div id="css3-animated-example">
            <?php
            if($arrCat){
                foreach($arrCat as $cate){
                    if($cate -> parent_id == 0){
                        $id = $cate -> id;
                        ?>
                        <h3 class="activev <?php if($parent_id == $id) echo 'open' ?> "><span class="arrows"></span><?php echo $cate -> name ?></h3>

                        <div>
                            <div class="content">
                                <ul class="m_n_v">
                                    <?php
                                    foreach($arrCat as $cate2){
                                        if($cate2 -> parent_id == $id){
                                            ?>
                                            <li class="<?php if($cateId == $cate2 -> id) echo 'active' ?>"><span class="arrows1"></span><a href="<?php echo $this->url('main', array('action' => 'category'), array('query' => array('id' => $cate2->id, 'parent_id' => $id,))); ?>"> <?php echo $cate2 -> name ?></a></li>
                                        <?php
                                        }
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>

                    <?php
                    }
                }
            }
            ?>

        </div>


    </div>
    <div id="sidebar">
        <?php echo $this->partial('sidebar'); ?>
    </div>
</div>
<div class="column_right">
    <div id="gallery" class="ad-gallery">
        <?php if(isset($arritem) && $arritem && count($arritem)){ ?>
            <div class="nen_bgs"></div>
            <div class="ad-image-wrapper">
            </div>
            <div class="ad-controls">
            </div>

            <div class="ad-nav">
                <div class="ad-thumbs">
                    <ul class="ad-thumb-list">
                        <?php

                        foreach($arritem as $item){
                            isset($item->arr_images) && $item->arr_images ? $images = unserialize($item->arr_images)[0] : $images = '';
                            ?>
                            <li>
                                <a href="<?php  if($images) echo $this->basePath().'/img/admin/items/'.$images; ?>">
                                    <img src="<?php  if($images) echo $this->basePath().'/img/admin/items/'.$images; ?>" title="<?php echo $item -> name ?> " class="image1">
                                </a>
                            </li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>
            </div>
        <?php
        }
        ?>
    </div>
    <div class="des">Mô tả</div>
    <div class="nd">
        <?Php if($category) echo $category -> description  ?>
    </div>
</div>